import Head from 'next/head'
import Image from 'next/image'
import s from '../styles/Home.module.css'
import L from 'next/link'
import A from '../components/A'

export default function Home() {
  return (
<>
<div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={s.navbar}>
        <A href={"/"} text='Главная' />
        <A href={"/users"} text='Список user' />
      </div>

    </div>
</>

  )
}
